### PR TITLE
Update retired Redis version to 6.0

### PR DESCRIPTION
**Pull request by SandraAhlgrimm**
## Purpose
Minor change to correct instruction for readme.

## Does this introduce a breaking change?
```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by SandraAhlgrimm** [comment]
I also updated redis to 6.0 to solve #21

**Comment by SandraAhlgrimm** [comment]
@euchungmsft I'd appreciate your review and merge :)

**Comment by SandraAhlgrimm** [comment]
Hi @aarthiem, I'd appreciate your review and merge if everything is fine!

**Comment by euchungmsft** [comment]
Updated to 'latest'

**Pull request closed without merging**
